/**
 * GAS Template — Master Configuration (CommonJS mirror of gas.config.ts).
 *
 * Node-evaluated build tools (tailwind.config.js, eas-cli) require() this file
 * because they cannot load the TypeScript gas.config.ts. It carries the FULL
 * config so it is safe even if Metro resolves it at runtime.
 *
 * Auto-generated by DevAgent — kept in lockstep with gas.config.ts.
 */

const gasConfig = {
  app: {
    name: "Arc",
    slug: "arc",
    description: "Arc is the app for finishing hard challenges and proving it. Start a time-boxed challenge, build an unbroken streak with one weekly freeze, earn a verified shareable proof card at the finish line, and stack every completed challenge into a permanent personal discipline record. The streak and the shareable proof are the product — Strava for self-discipline.",
    scheme: "arc",
    version: "1.0.0",
    minRuntimeVersion: "1.0.0",
    appStoreUrl: "",
    owner: "osritmos",
  },

  design: {
    mood: "bold",
    colors: {
      text: "#F5F0E8",
      error: "#C0392B",
      accent: "#D4A029",
      border: "#2A2A2A",
      primary: "#E8520A",
      success: "#4CAF7D",
      surface: "#1A1A1A",
      warning: "#D4A029",
      textDark: "#E8E0D0",
      secondary: "#F5F0E8",
      background: "#0D0D0D",
      borderDark: "#1F1F1F",
      primaryDark: "#B03A0A",
      surfaceDark: "#141414",
      textSecondary: "#888888",
      backgroundDark: "#080808",
      textSecondaryDark: "#666666",
    },
    typography: {
      bodyFont: "Manrope",
      monoFont: "Outfit",
      displayFont: "Josefin Sans",
      headingWeight: "700",
    },
    layout: {
      spacing: "comfortable",
      cardStyle: "filled",
      buttonStyle: "square",
      borderRadius: "none",
      navigationStyle: "minimal",
    },
  },

  features: {
    auth: {
      email: true,
      google: true,
      apple: true,
      twitter: false,
      github: false,
      facebook: false,
      discord: false,
      linkedin: false,
      microsoft: false,
      spotify: false,
      slack: false,
      twitch: false,
      notion: false,
      figma: false,
      biometric: {
        enabled: false,
        timeoutMinutes: 5,
      },
      magicLink: false,
      guestMode: false,
      mfa: false,
    },
    pushNotifications: {
      enabled: true,
      permissionTiming: "after_aha_moment",
      channels: [
        "daily_reminder",
        "streak_at_risk",
        "challenge_completion",
        "weekly_insight_ready",
        "freeze_auto_consumed",
      ],
    },
    inAppPurchases: {
      enabled: true,
      tiers: [
        {
          name: "Arc Free",
          productId: "arc_free",
          price: "$0",
          features: [
            "1 active challenge at a time",
            "Full curated challenge library (browse all, start one)",
            "Custom challenge creation",
            "Streak engine with weekly freeze",
            "Default proof card on completion",
            "Basic challenge history (last 3 completions)",
            "Daily local reminder notification",
            "Missed-day acknowledgment flow",
          ],
        },
        {
          name: "Arc Pro Monthly",
          productId: "arc_pro_monthly",
          price: "$8.99/month",
          features: [
            "Unlimited concurrent active challenges",
            "Full challenge history — every challenge ever started",
            "Weekly pattern insights (on-device: miss rate by day, momentum graph)",
            "Custom proof card themes (Ember, Bone, Obsidian, Minimal)",
            "Full badge gallery with all badge types",
            "Priority support",
          ],
          trialDays: 7,
        },
        {
          name: "Arc Pro Annual",
          productId: "arc_pro_annual",
          price: "$49.99/year",
          features: [
            "All Arc Pro Monthly features",
            "Save 53% vs monthly",
            "14-day free trial",
            "Exclusive 'Arc Lifer' badge in profile",
          ],
          trialDays: 14,
        },
      ],
      oneTimePurchases: [],
      credits: {
        enabled: false,
        currencyName: "credit",
        currencyNamePlural: "credits",
        iconName: "Coins",
        packs: [],
      },
      marketplace: {
        enabled: false,
        platformFeePercent: 0,
        sellerPayoutMethod: "stripe_connect",
        listingCategories: [],
        requiresApproval: true,
        escrowEnabled: false,
      },
    },
    analytics: {
      enabled: true,
      provider: "posthog",
      crashReporting: false,
      sessionRecording: false,
      featureFlags: false,
    },
    darkMode: {
      enabled: true,
      default: "dark",
    },
    offlineSync: {
      enabled: true,
      cachedEntities: [
        "active_challenge",
        "day_logs",
        "streak_data",
        "badges",
        "challenge_library",
        "user_preferences",
      ],
      syncStrategy: "on_reconnect",
      encrypted: false,
    },
    gamification: {
      enabled: true,
      elements: [
        "streak counter with ember ring",
        "weekly freeze mechanic",
        "challenge completion badges",
        "badge gallery with locked/earned states",
        "discipline record stats (total days logged, challenges finished, longest streak)",
        "completion ceremony with particle animation and badge reveal",
        "progress-to-finish-line bar with end date anchor",
      ],
    },
    onboarding: {
      enabled: true,
      steps: [
        "Welcome screen: ARC manifesto + ember ring animation + single 'Begin' CTA — no account required",
        "Challenge Picker: Browse curated 8–12 challenge library OR tap 'Build Your Own' to create custom challenge — category chips filter the list",
        "Commitment Screen: Consequence-forward formal contract — challenge name large, commitments numbered, freeze rule explained, single 'I Accept the Challenge' CTA with haptic + ring burst",
        "Reminder Setup: Time picker pre-set to 8:00 PM, privacy note confirming on-device storage, 'Set Reminder & Start Day 1' CTA — skip option available",
        "Lands on Today tab as Day 1 — daily commitments ready to check off, streak counter at 0 ready to begin",
      ],
    },
    helpSystem: true,
    search: {
      enabled: true,
      entities: ["challenge_library"],
      implementation: "client-side",
    },
    socialSharing: {
      enabled: true,
      content: ["proof_card_completion", "daily_progress_card", "streak_milestone_badge"],
      platforms: [
        "Instagram Stories",
        "TikTok",
        "Reddit",
        "X (Twitter)",
        "WhatsApp",
        "system share sheet",
      ],
    },
    i18n: {
      enabled: false,
      locales: ["en-US"],
      defaultLocale: "en-US",
    },
    media: {
      imagePicker: false,
      camera: false,
      audioPlayback: false,
      videoPlayback: false,
      fileUpload: false,
    },
    compliance: {
      attDialog: false,
      gdprConsent: false,
      ccpaNotice: false,
      ageGate: false,
      dataExport: true,
    },
    ads: {
      enabled: false,
      provider: "admob",
    },
    notifications: {
      enabled: true,
      categories: {
        transactional: {
          enabled: true,
          defaultOn: true,
        },
        product: {
          enabled: true,
          defaultOn: true,
        },
        marketing: {
          enabled: true,
          defaultOn: false,
        },
      },
      receiptPolling: {
        enabled: true,
        intervalMinutes: 5,
        expireAfterMinutes: 30,
      },
    },
    telemetry: {
      enabled: true,
      flushIntervalMs: 30000,
      maxQueueSize: 200,
      debugOverlay: false,
      ingestUrl: "https://goodspeed.app/api/telemetry/ingest",
    },
    anonymousAuth: {
      enabled: false,
      tables: [],
    },
    backgroundFetch: false,
    csvExport: false,
    showBuiltWithBadge: false,
  },

navigation: {
    tabs: [
      {
        id: "settings",
        label: "Settings",
        icon: "Settings",
        file: "settings",
      },
    ],
    hiddenScreens: ["today", "journey"],
    modals: ["paywall"],
  },

  releaseChannels: {
    current: "production",
    storeUrl: {
      ios: "",
      android: "",
    },
  },

  compliance: {
    accountDeletionGracePeriod: {
      days: 30,
    },
    allowImmediateDeletion: true,
    exportTables: [
      "profiles",
      "push_tokens",
      "notifications",
      "user_bookmarks",
      "feedback",
      "consent_log",
    ],
    consentBannerRequired: "eu_only",
  },

  ui: {
    breakpoints: {
      tablet: 600,
      desktop: 1024,
    },
    honorDynamicType: true,
    honorReducedMotion: true,
  },

  multiTenancy: {
    enabled: false,
    defaultRole: "member",
  },

  integrations: {
    oauthProviders: [],
  },

  growth: {
    experimentsEnabled: true,
    defaultBackgroundSyncInterval: 60000,
    referralCodeLength: 8,
  },

  media: {
    provider: "supabase",
    maxUploadBytes: 10485760,
    allowedContentTypes: ["image/jpeg", "image/png", "image/webp"],
    defaultBucket: "uploads",
    maxImageEdge: 2048,
    signedUrlTtlSeconds: 3600,
  },

  search: {
    defaultLanguage: "en",
    defaultLimit: 20,
    maxLimit: 100,
  },

  realtime: {
    presenceTimeoutMs: 30000,
    autoReconnect: true,
    defaultRetries: 3,
  },

  llm: {
    provider: "anthropic",
    defaultChatModel: "claude-opus-4-1",
    defaultEmbedModel: "claude-3-5-sonnet-20241022",
    defaultTranscribeModel: "whisper-1",
    costScope: "monthly",
    budgetPeriod: "month",
  },

  backend: {
    supabase: {
      url: process.env.EXPO_PUBLIC_SUPABASE_URL ?? '',
      anonKey: process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY ?? '',
    },
    revenuecat: {
      iosKey: process.env.EXPO_PUBLIC_REVENUECAT_API_KEY_IOS ?? '',
      androidKey: process.env.EXPO_PUBLIC_REVENUECAT_API_KEY_ANDROID ?? '',
    },
    posthog: {
      apiKey: process.env.EXPO_PUBLIC_POSTHOG_API_KEY ?? '',
      host: process.env.EXPO_PUBLIC_POSTHOG_HOST ?? 'https://us.i.posthog.com',
    },
    telemetry: {
      // EXPO_PUBLIC_TELEMETRY_INGEST_SECRET — ingest identity HMAC key. Public-bundle
      // value, not an auth secret. TelemetryProvider reads .ingestSecret at module
      // init; the field MUST be present (empty string is OK) or the React tree
      // crashes on first mount. See gas-template GasBackendConfig.telemetry.
      ingestSecret: process.env.EXPO_PUBLIC_TELEMETRY_INGEST_SECRET ?? '',
    },
    stripe: {
      // Same always-emit pattern as telemetry: safe-off empty string at codegen,
      // runtime decides whether to init Stripe based on marketplace.enabled.
      publishableKey: process.env.EXPO_PUBLIC_STRIPE_PUBLISHABLE_KEY ?? '',
    },
  },
};

module.exports = { gasConfig };
module.exports.default = gasConfig;
